op_names = [
    'vote',
    'comment',
    'transfer',
    'transfer_to_vesting',
    'withdraw_vesting',
    'account_create_by_committee',
    'account_create',
    'account_create_with_delegation',
    'account_update',
    'witness_update',
    'account_witness_vote',
    'account_witness_proxy',
    'delete_comment',
    'comment_options',
    'set_withdraw_vesting_route_to_account',
    'set_withdraw_vesting_route_to_dev_pool',
    'prove_authority',
    'request_account_recovery',
    'recover_account',
    'change_recovery_account',
    'escrow_approve',
    'escrow_dispute',
    'escrow_release',
    'escrow_transfer',
    'decline_voting_rights',
    'delegate_vesting_shares',
    'create_budget',
    'close_budget',
    'author_reward',
    'comment_benefactor_reward',
    'comment_payout_update',
    'comment_reward',
    'curation_reward',
    'fill_vesting_withdraw',
    'hardfork',
    'producer_reward',
    'return_vesting_delegation',
    'shutdown_witness',
    'liquidity_reward',
    'interest',
    'fill_order',
    'fill_transfer_from_savings',
    'proposal_create'
]

#: assign operation ids
operations = dict(zip(op_names, range(len(op_names))))
